chore: Remove support for dbt 0.X (#464)
* Remove 0.X from testing

* Remove 0.X from supported versions list

* Remove dbt version checks

* Add dbt<1.0.0 exception

* Remove copied code for 0.X dbt versions

* adapt tests to not handle 0.X dbt version

diff --git a/.github/actions/setup-local-fal/action.yml b/.github/actions/setup-local-fal/action.yml
--- a/.github/actions/setup-local-fal/action.yml
+++ b/.github/actions/setup-local-fal/action.yml
@@ -38,13 +38,13 @@ runs:
     - name: Install dbt
       shell: bash
       run: |
-        if [[ '${{ inputs.dbt }}' =~ ^0.*$ ]]
+        if [[ '${{ inputs.dbt }}' == 'latest' ]]
         then
-          pip install dbt==${{ inputs.dbt }}
-          pip install dbt-${{ inputs.adapter }}==${{ inputs.dbt }}
+          pip install dbt-${{ inputs.adapter }}
         elif [[ '${{ inputs.dbt }}' =~ ^1.*$ ]]
         then
           pip install dbt-${{ inputs.adapter }}==${{ inputs.dbt }}
         else
-          pip install dbt-${{ inputs.adapter }}
+          echo "Invalid dbt version to install"
+          exit 2
         fi
